### ISSUE TITLE
Error from Event after changing to your XML

### ISSUE THREAD

**Issue by iAlpex** [ronancpl/HeavenMS#162]
After i started to use your XML's i got this error avax.script.ScriptException: ReferenceError: "importPackage" is not defined in <eval> at line number 34
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
	at javax.script.AbstractScriptEngine.eval(Unknown Source)
	at scripting.AbstractScriptManager.getInvocable(AbstractScriptManager.java:70)
	at scripting.event.EventScriptManager.<init>(EventScriptManager.java:54)
	at net.server.channel.Channel.<init>(Channel.java:106)
	at net.server.Server.run(Server.java:328)
	at net.server.Server.main(Server.java:368)
Caused by: <eval>:34 ReferenceError: "importPackage" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1441)
	at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:34)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 9 more

**Comment by ronancpl** [comment]
Use of Java7 is necessary to properly solve this issue.

**Comment by iAlpex** [comment]
i am using java 7

**Comment by jaydenseah** [comment]
@iAlpex Do you have other version of Java installed in your machine? If so, please try to remove and left only Java & JDK 7

**Comment by ronancpl** [comment]
@iAlpex It could be that the subversion you are using doesn't have the required packages, given you have set properly Java 7 on your machine. Version being used here is 7u79.

**Comment by iAlpex** [comment]
so i cannot use version 7u21? That is unfortunate

**Comment by iAlpex** [comment]
Fixed the issue thanks!
