### ISSUE TITLE
Server/Client Login

### ISSUE THREAD

**Issue by AmirAvram** [ronancpl/HeavenMS#164]
Hello, I've followed the guide on the readme file, running on localhost.
the server starts correctly but when I try to login im getting this(cmd trace):
```
HeavenMS v83 starting up.

Skills loaded in 1.982 seconds
Items loaded in 0.516 seconds
Quest loaded in 2.872 seconds

Starting world 0
    Channel 1: Listening on port 7575
    Channel 2: Listening on port 7576
    Channel 3: Listening on port 7577
Finished loading world 0

Listening on port 8484


HeavenMS is now online.

Log: sessions.txt
IoSession with /127.0.0.1:53281 opened on 26-01-2018 18:07
java.security.InvalidKeyException: Illegal key size or default parameters
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1011)
        at javax.crypto.Cipher.implInit(Cipher.java:786)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:849)
        at javax.crypto.Cipher.init(Cipher.java:1213)
        at javax.crypto.Cipher.init(Cipher.java:1153)
        at tools.MapleAESOFB.<init>(MapleAESOFB.java:64)
        at net.MapleServerHandler.sessionOpened(MapleServerHandler.java:116)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.sessionOpened(DefaultIoFilterChain.java:635)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:359)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$800(DefaultIoFilterChain.java:47)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionOpened(DefaultIoFilterChain.java:745)
        at org.apache.mina.core.filterchain.IoFilterAdapter.sessionOpened(IoFilterAdapter.java:81)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:359)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$800(DefaultIoFilterChain.java:47)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionOpened(DefaultIoFilterChain.java:745)
        at org.apache.mina.core.filterchain.IoFilterAdapter.sessionOpened(IoFilterAdapter.java:81)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:359)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireSessionOpened(DefaultIoFilterChain.java:352)
        at org.apache.mina.core.service.IoServiceListenerSupport.fireSessionCreated(IoServiceListenerSupport.java:212)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.addNow(AbstractPollingIoProcessor.java:534)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.handleNewSessions(AbstractPollingIoProcessor.java:501)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$400(AbstractPollingIoProcessor.java:67)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1116)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.security.InvalidKeyException: Illegal key size or default parameters
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1011)
        at javax.crypto.Cipher.implInit(Cipher.java:786)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:849)
        at javax.crypto.Cipher.init(Cipher.java:1213)
        at javax.crypto.Cipher.init(Cipher.java:1153)
        at tools.MapleAESOFB.<init>(MapleAESOFB.java:64)
        at net.MapleServerHandler.sessionOpened(MapleServerHandler.java:117)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.sessionOpened(DefaultIoFilterChain.java:635)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:359)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$800(DefaultIoFilterChain.java:47)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionOpened(DefaultIoFilterChain.java:745)
        at org.apache.mina.core.filterchain.IoFilterAdapter.sessionOpened(IoFilterAdapter.java:81)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:359)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$800(DefaultIoFilterChain.java:47)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionOpened(DefaultIoFilterChain.java:745)
        at org.apache.mina.core.filterchain.IoFilterAdapter.sessionOpened(IoFilterAdapter.java:81)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:359)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireSessionOpened(DefaultIoFilterChain.java:352)
        at org.apache.mina.core.service.IoServiceListenerSupport.fireSessionCreated(IoServiceListenerSupport.java:212)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.addNow(AbstractPollingIoProcessor.java:534)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.handleNewSessions(AbstractPollingIoProcessor.java:501)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$400(AbstractPollingIoProcessor.java:67)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1116)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
disconnect by exception
org.apache.mina.filter.codec.ProtocolDecoderException: java.lang.IllegalStateException: Cipher not initialized (Hexdump: 29 BC 2B BC 08 60)
        at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:242)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
        at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Cipher not initialized
        at javax.crypto.Cipher.checkCipherState(Cipher.java:1672)
        at javax.crypto.Cipher.doFinal(Cipher.java:2079)
        at tools.MapleAESOFB.crypt(MapleAESOFB.java:96)
        at net.mina.MaplePacketDecoder.doDecode(MaplePacketDecoder.java:67)
        at org.apache.mina.filter.codec.CumulativeProtocolDecoder.decode(CumulativeProtocolDecoder.java:176)
        at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:232)
        ... 15 more
```

**Comment by ronancpl** [comment]
Check again the JCE part of the tutorial to solve this issue.

**Comment by AmirAvram** [comment]
@ronancpl im actually missing this part:

> Overwrite whenever prompted with the JAR files under "jce_policy-7/UnlimitedJCEPolicy" in these Java folders:
> 
> C:\Program Files\Java\jre7\lib
> C:\Program Files\Java\jre7\lib\ext
> C:\Program Files\Java\jre7\lib\security
> C:\Program Files\Java\jdk1.7.0_01\lib
> C:\Program Files\Java\jdk1.7.0_01\jre\lib
> C:\Program Files\Java\jdk1.7.0_01\jre\lib\ext
> C:\Program Files\Java\jdk1.7.0_01\jre\lib\security

as it's just not prompting me to replace them.
