### ISSUE TITLE
some mistakes！

### ISSUE THREAD

**Issue by leihen08** [ronancpl/HeavenMS#204]
Error thrown: quests/29508.txt
java.lang.NoSuchMethodException: no such method: end
	at com.sun.script.javascript.RhinoScriptEngine.invoke(Unknown Source)
	at com.sun.script.javascript.RhinoScriptEngine.invokeFunction(Unknown Source)
	at scripting.quest.QuestScriptManager.end(QuestScriptManager.java:131)
	at net.server.channel.handlers.QuestActionHandler.handlePacket(QuestActionHandler.java:110)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:162)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

---------------------------------
java.lang.NoSuchMethodException: no such method: end
	at com.sun.script.javascript.RhinoScriptEngine.invoke(Unknown Source)
	at com.sun.script.javascript.RhinoScriptEngine.invokeFunction(Unknown Source)
	at scripting.quest.QuestScriptManager.end(QuestScriptManager.java:131)
	at net.server.channel.handlers.QuestActionHandler.handlePacket(QuestActionHandler.java:110)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:162)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

---------------------------------

**Comment by leihen08** [comment]
NPC Hanako(9209006) is not coded.
NPC Tae Gong(9209005) is not coded.
NPC Mr. Oh(9209002) is not coded.
NPC Lung Tup(9209003) is not coded.
NPC Lena(9209004) is not coded.
NPC Lazy Daisy(9209007) is not coded.
NPC Lena(9209004) is not coded.
NPC Spiegelmann(2042002) is not coded.

**Comment by leihen08** [comment]
disconnect by exception
org.apache.mina.core.write.WriteToClosedSessionException
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.clea
uestQueue(AbstractPollingIoProcessor.java:638)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.remo
tractPollingIoProcessor.java:590)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.remo
s(AbstractPollingIoProcessor.java:560)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.acce
stractPollingIoProcessor.java:67)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Proc
(AbstractPollingIoProcessor.java:1132)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservi
e.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown So
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown S
        at java.lang.Thread.run(Unknown Source)

**Comment by ronancpl** [comment]
Ok, addressed most of these issues:
Medal quests are in general not implemented. Corrected the medal script now to solve the "no such method" problem.
Disabled the 7th day market area since that event area is not implemented as a whole.

**Comment by leihen08** [comment]
Thanks for your fix, can I know what caused this error?
Why are pets unable to retrieve items?
PacketHandler
net.server.channel.handlers.GeneralChatHandler.txt
Error for player ; Cherry on map ; 101000000 - account ; leihen
All: 31 00 14 00 21 69 74 65 6D 20 73 6B 79 35 32 31 20 34 30 33 31 30 35 39 00
Now: 00
java.lang.NumberFormatException: For input string: "sky521"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at client.command.Commands.executeHeavenMsCommandLv2(Commands.java:1230)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2922)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMSPlayerCommand(Commands.java:2949)
	at net.server.channel.handlers.GeneralChatHandler.handlePacket(GeneralChatHandler.java:62)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:162)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

---------------------------------
Error for player ; Cherry on map ; 101000000 - account ; leihen
All: 31 00 14 00 21 69 74 65 6D 20 73 6B 79 35 32 31 20 34 30 33 31 30 35 39 00
Now: 00
java.lang.NumberFormatException: For input string: "sky521"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at client.command.Commands.executeHeavenMsCommandLv2(Commands.java:1230)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2922)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMsCommand(Commands.java:2941)
	at client.command.Commands.executeHeavenMSPlayerCommand(Commands.java:2949)
	at net.server.channel.handlers.GeneralChatHandler.handlePacket(GeneralChatHandler.java:62)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:162)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

---------------------------------
This error belongs to autoban?

**Comment by ronancpl** [comment]
Not related to autoban. Check your input syntax: "!item <itemid> <quantity>", itemid must be the numeric identity of the item you want to generate.

**Comment by leihen08** [comment]
Thank. I know! Pay tribute to your work！

**Comment by ronancpl** [comment]
Thanks! Since the other issues are already dealt with locally here I'm closing this.
