### ISSUE TITLE
Player kills doesn't count on certain quests

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#243]
Odd issue...
only happening with a white knight level 76 with dragon pet evolved, i can't reproduce this so far.

quest: Parwen´s lab (quest lvl 70)
npc : parwen
map: hideen street (authorized personnel only) 
player needs to kill 200 saites and kills won't count.

quest: Alcadno and the missing alchemist (quest lvl 70)
npc : maed
map: Magatia: Alcadno Society.
player needs to kill 100 homunculus and kills won't count.

so far, this is the only error in console i see with this white knight player:
https://www.dropbox.com/s/3uqx07sgmud16q8/bugpetplayer.png?dl=0

here's the log from another one:
```
MapleCharacter.mobKilled. CID: 68 last Quest Processed: 8185
java.lang.NullPointerException
	at server.quest.requirements.PetRequirement.check(PetRequirement.java:58)
	at server.quest.MapleQuest.canComplete(MapleQuest.java:260)
	at client.MapleCharacter.updateQuestMobCount(MapleCharacter.java:6529)
	at server.life.MapleMonster.giveExpToCharacter(MapleMonster.java:516)
	at server.life.MapleMonster.distributeExperience(MapleMonster.java:449)
	at server.life.MapleMonster.killBy(MapleMonster.java:521)
	at server.maps.MapleMap.killMonster(MapleMap.java:1348)
	at server.maps.MapleMap.killMonster(MapleMap.java:1272)
	at server.maps.MapleMap.damageMonster(MapleMap.java:1240)
	at net.server.channel.handlers.AbstractDealDamageHandler.applyAttack(AbstractDealDamageHandler.java:505)
	at net.server.channel.handlers.CloseRangeDamageHandler.handlePacket(CloseRangeDamageHandler.java:189)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:167)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ronancpl** [comment]
Pet quest issue solved.
