### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#285]
I've gotten this twice now after the server has been up for a while. Console gets spammed with NullPointerExceptions and many of the commands, etc. don't work properly

```java
java.lang.NullPointerException
	at server.maps.MapleMap$11.sendPackets(MapleMap.java:1923)
	at server.maps.MapleMap.spawnAndAddRangedMapObject(MapleMap.java:396)
	at server.maps.MapleMap.spawnMonster(MapleMap.java:1920)
	at server.maps.MapleMap.spawnMonster(MapleMap.java:1907)
	at server.maps.MapleMap.respawn(MapleMap.java:3522)
	at net.server.channel.Channel$respawnMaps.run(Channel.java:426)
	at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Possibly related
```java
java.lang.NullPointerException
	at server.maps.MapleMapFactory.loadMapFromWz(MapleMapFactory.java:104)
	at server.maps.MapleMapFactory.getMap(MapleMapFactory.java:318)
	at net.server.channel.Channel$2.run(Channel.java:628)
	at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ronancpl** [comment]
To get NullPointerException there MapleClient c = null. This is an odd case, since to a player's client be null, a player should have already quit the world server for 5 minutes.
So it seems some bottleneck is happening inside spawnAndAddRangedMapObject, which holds chrRLock and objectWLock.

**Comment by MedicOP** [comment]
Actually @online might break because of something else. MapleCharacter.getMap() returns null:

```java
Error thrown: PacketHandler/net.server.channel.handlers.GeneralChatHandler.txt
java.lang.NullPointerException
        at client.command.commands.gm0.OnlineCommand.execute(OnlineCommand.java:44)
        at client.command.CommandsExecutor.handle(CommandsExecutor.java:103)
        at net.server.channel.handlers.GeneralChatHandler.handlePacket(GeneralChatHandler.java:53)
        at net.MapleServerHandler.messageReceived(MapleServerHandler.java:186)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
        at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
        at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
        at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by MedicOP** [comment]
New info: It seems that the player shows up in 2 channels.

When I type @online2, I see the player in both channel 1 and channel 2, which is obviously not possible. 

When I try to !warpto the player in channel 2, it says they're in channel 1.

**Comment by MedicOP** [comment]
These errors are possibly related as well

```java
java.lang.NullPointerException
	at server.maps.MapMonitor.cancelAction(MapMonitor.java:47)
	at server.maps.MapMonitor.access$000(MapMonitor.java:28)
	at server.maps.MapMonitor$1.run(MapMonitor.java:40)
	at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```java
java.lang.NullPointerException
	at server.maps.MapleMap.calcPointBelow(MapleMap.java:469)
	at server.maps.MapleMap.calcDropPos(MapleMap.java:537)
	at server.maps.MapleMap.dropFromReactor(MapleMap.java:741)
	at scripting.reactor.ReactorActionManager$1.run(ReactorActionManager.java:174)
	at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
