### ISSUE TITLE
Dojo loadMapFromWz NPE

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#344]
```java
java.lang.NullPointerException
	at server.maps.MapleMapFactory.loadMapFromWz(MapleMapFactory.java:175)
	at server.maps.MapleMapFactory.getMap(MapleMapFactory.java:372)
	at net.server.channel.Channel$2.run(Channel.java:628)
	at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by MedicOP** [comment]
Fixed in https://github.com/ronancpl/HeavenMS/pull/351
