### ISSUE TITLE
NPE EventInstanceManager.monsterKilled

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#364]
I keep seeing this error a lot across many server restarts.

No idea why it happens

```java
java.lang.NullPointerException
	at scripting.event.EventInstanceManager.monsterKilled(EventInstanceManager.java:493)
	at server.life.MapleMonster.dispatchMonsterKilled(MapleMonster.java:721)
	at server.maps.MapleMap.killMonster(MapleMap.java:1265)
	at server.maps.MapleMap.killAllMonsters(MapleMap.java:1416)
	at server.maps.MapleMap.clearMapObjects(MapleMap.java:3976)
	at server.maps.MapleMap.dispose(MapleMap.java:4080)
	at server.maps.MapleMapFactory.dispose(MapleMapFactory.java:481)
	at scripting.event.EventInstanceManager$4.run(EventInstanceManager.java:639)
	at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by MedicOP** [comment]
Related

```java
javax.script.ScriptException: sun.org.mozilla.javascript.EcmaError: TypeError: Cannot call method "getProperty" of null (<Unknown source>#129) in <Unknown source> at line number 129
	at com.sun.script.javascript.RhinoScriptEngine.invoke(RhinoScriptEngine.java:300)
	at com.sun.script.javascript.RhinoScriptEngine.invokeFunction(RhinoScriptEngine.java:258)
	at scripting.npc.NPCScriptManager.start(NPCScriptManager.java:97)
	at scripting.npc.NPCScriptManager.start(NPCScriptManager.java:67)
	at net.server.channel.handlers.NPCTalkHandler.handlePacket(NPCTalkHandler.java:67)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:186)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.org.mozilla.javascript.EcmaError: TypeError: Cannot call method "getProperty" of null (<Unknown source>#129)
	at sun.org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3689)
	at sun.org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3667)
	at sun.org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3695)
	at sun.org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3714)
	at sun.org.mozilla.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:3731)
	at sun.org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2257)
	at sun.org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2250)
	at sun.org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1317)
	at sun.org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at sun.org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at sun.org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at com.sun.script.javascript.RhinoScriptEngine$1.superDoTopCall(RhinoScriptEngine.java:116)
	at com.sun.script.javascript.RhinoScriptEngine$1.doTopCall(RhinoScriptEngine.java:109)
	at sun.org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
	at sun.org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at com.sun.script.javascript.RhinoScriptEngine.invoke(RhinoScriptEngine.java:294)
	... 26 more
```

**Comment by MedicOP** [comment]
> 
> 
> Found a similar error stack trace log, may be related as well:
> 
> ```
> java.lang.NullPointerException
>         at scripting.event.EventInstanceManager.monsterKilled(EventInstanceManager.java:493)
>         at server.life.MapleMonster.dispatchMonsterKilled(MapleMonster.java:700)
>         at server.maps.MapleMap.killMonster(MapleMap.java:1270)
>         at server.maps.MapleMap.killAllMonsters(MapleMap.java:1421)
>         at server.maps.MapleMap.clearMapObjects(MapleMap.java:3897)
>         at server.maps.MapleMap.dispose(MapleMap.java:4001)
>         at server.maps.MapleMapFactory.dispose(MapleMapFactory.java:488)
>         at scripting.event.EventInstanceManager$4.run(EventInstanceManager.java:639)
>         at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>         at java.lang.Thread.run(Thread.java:745)
> ```

Probably just the same as mine. My line numbers might be a bit off cause I'm not using the exact same as master

**Comment by MedicOP** [comment]
Actually the cause of this problem is pretty simple.

EventInstanceManager.dispose() sets em = null. Then schedules the mobs to be killed 60 seconds later, which causes the NPE.

Should just ask a null check in monsterKilled

**Comment by ronancpl** [comment]
This issue should already be cleared by the latest update (moved em = null assignment to after event map factory dispose). Fundamentally, no kind of interaction with the event instance should happen from the moment eim.dispose() is triggered.

If this theoretical basis is inaccurate, and this issue still persists, let me know so that the PR #380 takes place.
