### ISSUE TITLE
LoginPasswordHandler error

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#396]
Similar to issue #280, I get this error all the time, have been getting it since day 1

```java
All: 01 00 06 00 70 69 6F 6F 70 33 0B 00 61 31 32 33 34 35 36 37 38 39 61 00 00 00 00 00 00 BB AE C6 F2 00 00 00 00 CC BB 00 00 00 00 02 00 00 00 00 00 00
Now: 00 00 00 00 CC BB 00 00 00 00 02 00 00 00 00 00 00
java.lang.RuntimeException: getLoginState - MapleClient AccID: 0
	at client.MapleClient.getLoginState(MapleClient.java:786)
	at client.MapleClient.finishLogin(MapleClient.java:439)
	at net.server.handlers.login.LoginPasswordHandler.handlePacket(LoginPasswordHandler.java:126)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:200)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ronancpl** [comment]
Then issue rests within `MapleClient.login()`, where players are validated to login (loginok = 0) whilst having MapleClient.accId unsetted.

**Comment by MedicOP** [comment]
If that's the case, then the error could simply be hidden, right?
