### ISSUE TITLE
MapleSkillBookInformationParser Fails on Wetbottom quest

### ISSUE THREAD

**Issue by CanIGetaPR** [ronancpl/HeavenMS#457]
```
<imgdir name="2021">
    <imgdir name="1">
      <int name="exp" value="5000" />
      <imgdir name="item">
        <imgdir name="0">
          <int name="id" value="4000013" />
          <int name="count" value="-50" />
        </imgdir>
        <imgdir name="1">
          <int name="id" value="4000017" />
          <int name="count" value="-5" />
        </imgdir>
        <imgdir name="2">
          <int name="id" value="4031014" />
          <int name="count" value="1" />
        </imgdir>
      </imgdir>
    </imgdir>
    <imgdir name="0" />
  </imgdir>
```

**Comment by CanIGetaPR** [comment]
```
Failed to read Quest.wz file. Line 5287:       <imgdir name="item">
java.lang.NumberFormatException: For input string: "item"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at server.MapleSkillbookInformationProvider.translateActToken(MapleSkillbookInformationProvider.java:217)
	at server.MapleSkillbookInformationProvider.fetchSkillbooksFromQuests(MapleSkillbookInformationProvider.java:243)
	at server.MapleSkillbookInformationProvider.loadSkillbooks(MapleSkillbookInformationProvider.java:358)
	at server.MapleSkillbookInformationProvider.<clinit>(MapleSkillbookInformationProvider.java:89)
	at net.server.Server.init(Server.java:971)
	at net.server.Server.main(Server.java:978)
```

**Comment by ronancpl** [comment]
Oh, I see. Unexpected scenario for `<imgdir name="0" />`.

**Comment by ronancpl** [comment]
Issue fixed.
