### ISSUE TITLE
timestampElapsedDays Error

### ISSUE THREAD

**Issue by maple006** [ronancpl/HeavenMS#467]
ExceptionCaught.txt

java.lang.NullPointerException
	at client.processor.FredrickProcessor.timestampElapsedDays(FredrickProcessor.java:88)
	at client.processor.FredrickProcessor.runFredrickSchedule(FredrickProcessor.java:195)
	at net.server.worker.FredrickWorker.run(FredrickWorker.java:31)
	at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by ronancpl** [comment]
Found out try reason behind this issue: a character has been deleted!

Currently characterid contents within `fredstorage` table are not being cleared, which leads into the issue as soon as the `SELECT * FROM fredstorage f LEFT JOIN` SQL command recovers an inexistent `cid`...

Thanks for reporting!
