### ISSUE TITLE
error ShutdownCommand

### ISSUE THREAD

**Issue by maple006** [ronancpl/HeavenMS#472]
!shutting
When working successfully

Successfully shut down Channel 1 on World 0

Shutting down Channel 2 on World 0
Successfully shut down Channel 2 on World 0

Shutting down Channel 3 on World 0
Successfully shut down Channel 3 on World 0

Finished shutting down world 0

Worlds + Channels are offline.
Shutting down the server!

Exception in thread "Thread-0" java.lang.NullPointerException
        at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1051)
        at java.util.Collections$UnmodifiableList.<init>(Collections.java:1204)
        at java.util.Collections.unmodifiableList(Collections.java:1190)
        at net.server.Server.getWorlds(Server.java:246)
        at net.server.Server.shutdownInternal(Server.java:1739)
        at net.server.Server.access$100(Server.java:106)
        at net.server.Server$2.run(Server.java:1732)
        at java.lang.Thread.run(Thread.java:745)
Press any key to continue . . .

**Comment by ronancpl** [comment]
This should be clear now, thanks for pointing this issue out!
